"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";

import PageHeader from "@/components/dashboard/PageHeader";
import SessionVideoInput, {
  type VideoInputMode,
} from "@/components/sessions/SessionVideoInput";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { USE_API } from "@/lib/api-config";
import type { Session } from "@/types";
import {
  fetchSession,
  uploadSessionFiles,
} from "@/services/session-upload-service";

export default function UploadSessionPage() {
  const router = useRouter();
  const params = useParams<{ sessionId: string }>();
  const sessionId = params.sessionId;

  const [session, setSession] = useState<Session | null>(null);
  const [videoMode, setVideoMode] = useState<VideoInputMode>("upload");
  const [videoFile, setVideoFile] = useState<File | undefined>();
  const [expectedWord, setExpectedWord] = useState("Elephant");
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (!sessionId || !USE_API) {
      return;
    }

    fetchSession(sessionId)
      .then(setSession)
      .catch(() => setError("Could not load session details."));
  }, [sessionId]);

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");

    if (!videoFile) {
      setError("Please upload or record a therapy video.");
      return;
    }

    setSubmitting(true);

    try {
      const updated = await uploadSessionFiles(sessionId, {
        video: videoFile,
        expectedWord,
      });

      const query = new URLSearchParams();
      if (updated.reportId) {
        query.set("reportId", updated.reportId);
      }
      if (updated.patientId) {
        query.set("patientId", updated.patientId);
      }

      router.push(`/sessions/${sessionId}/processing?${query.toString()}`);
    } catch (uploadError) {
      setError(
        uploadError instanceof Error ? uploadError.message : "Upload failed."
      );
      setSubmitting(false);
    }
  }

  return (
    <div className="mx-auto max-w-3xl space-y-8">
      <PageHeader
        title="Upload session video"
        description="Add a recorded or live-captured video. Annotated video and CSV are generated by the AI pipeline."
      />

      {session ? (
        <Card className="border-0 shadow-sm ring-1 ring-border/60">
          <CardHeader>
            <CardTitle>{session.patientName}</CardTitle>
            <CardDescription>
              Session time: {session.dateLabel}
              {session.doctorNotes ? ` • ${session.doctorNotes}` : ""}
            </CardDescription>
          </CardHeader>
        </Card>
      ) : null}

      <Card className="border-0 shadow-sm ring-1 ring-border/60">
        <CardHeader>
          <CardTitle>Session video</CardTitle>
          <CardDescription>
            The session date stays as originally scheduled. Only the video is
            uploaded now for analysis.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form className="space-y-6" onSubmit={handleSubmit}>
            <SessionVideoInput
              mode={videoMode}
              onModeChange={setVideoMode}
              videoFile={videoFile}
              onVideoFileChange={setVideoFile}
              expectedWord={expectedWord}
              onExpectedWordChange={setExpectedWord}
              disabled={submitting}
            />

            {error ? <p className="text-sm text-[#EF4444]">{error}</p> : null}

            <div className="flex gap-3">
              <Button type="submit" disabled={submitting || !sessionId}>
                {submitting ? "Uploading..." : "Upload & analyze"}
              </Button>
              <Button variant="outline" asChild>
                <Link href="/sessions">Cancel</Link>
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
